modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="items_displayed"
version="2.2.7"
displayName="Items Displayed"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/items-displayed"
logoFile="logo.png"
credits="Jusey1, Freedinner"
authors="Jusey1, Freedinner"
description="Allows the display of specific items."

[[mixins]]
config="display.mixins.json"

[[dependencies.items_displayed]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.items_displayed]]
    modId="alexscaves"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.items_displayed]]
    modId="cloudstorage"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.items_displayed]]
    modId="create"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.items_displayed]]
    modId="ecologics"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.items_displayed]]
    modId="friendsandfoes"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.items_displayed]]
    modId="galosphere"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.items_displayed]]
    modId="kobolds"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.items_displayed]]
    modId="spawn"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.items_displayed]]
    modId="supplementaries"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"