modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="items_displayed"
version="2.1.0"
displayName="Items Displayed"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/items-displayed"
logoFile="logo.png"
credits="Jusey1, Freedinner"
authors="Jusey1, Freedinner"
description="Allows the display of specific items."

[[mixins]]
config="display.mixins.json"

[[dependencies.display]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.2,)"
    ordering="NONE"
    side="BOTH"
